### ISSUE TITLE
Allow source_context to evaluate build env vars

### ISSUE THREAD

**Issue by christophermancini** [dpb587/github-status-resource#12] opened 2018-06-12 17:24 UTC
This would allow different jobs within the pipeline to post to separate statuses and support simple copy/paste between pipelines.

**Comment by dpb587** [comment] 2018-06-13 05:03
Closing as duplicate of #8 - feel free to add additional comments or ideas there.

**Closed as completed by dpb587** 2018-06-13 05:03 UTC

**Comment by christophermancini** [comment] 2018-06-13 14:23
My bad!
